baseurl = "https://www.e39source.com" 
title = "E39Source"
theme = "E39Source"
themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
[pagination]
pagerSize = 10

# not pluralize title pages by default
pluralizelisttitles = false

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1

[[menu.main]]
    identifier = "service"
    name       = "Service"
    url        = "/service/"
    weight     = 2

[[menu.main]]
    name       = "Donate"
    identifier = "menu.donate"
    url        = "https://donate.stripe.com/bIY16N13ccyY5FK8ww"
    weight     = 9

[[menu.main]]
    name       = "products"
    identifier = "menu.products"
    url        = "/products/"
    weight     = 3

[[menu.main]]
    name       = "Videos"
    identifier = "menu.videos"
    url        = "http://www.youtube.com/E39Source"
    weight     = 8

[[menu.main]]
    name       = "Articles"
    identifier = "menu.blog"
    url        = "/categories/e39-m5-bmw/"
    weight     = 7

[[menu.main]]
    name       = "Downloads"
    identifier = "menu.faq"
    url        = "/downloads/"
    weight     = 4

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 5

[[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about-us/"
    weight     = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Phone"
    url = "tel:+12 34 567 89 01"
    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/devcows/hugo-universal-theme"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:support@e39source.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"


[params]
    viewMorePostLink = "/blog/"
    author = "Ryan Schultz"
    title="location"
    defaultKeywords = ["E39Source", "BMW", "go"]
    mainSections = ["blog"]
    defaultDescription = "E39Source BMW"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/E39Source-Logo.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/f/mjvnvgrq"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>E39Source is a ground-breaking BMW enthusiast-operated business that offers top-tier service, quality parts, consulting, and useful resources to promote the global preservation of the BMW E39 5-Series (1994-2003), specializing with the pinnacle model, the M5. <br/><br/> E39Source graciously credits the logo design work to Matt McComb of Ironfuzz Design. </p>"
    copyright = "Copyright (c) 2023 E39Source; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "Universal"

    logo = "img/E39Source-Logo.png"
    logo_small = "img/E39Source-Logo.png"
    location_url = "/location"
    address = """<p class="text-uppercase"><strong></strong>
        <br>301 Enterprise St
        <br>Suite 1
        <br>Escondido
        <br>California
        <br>
        <strong>United States</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = false
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have had the privilege of working with hundreds of enthusiasts and always love to see them drive out of our facility happy and satisfied!  Have a look at what our clients have said about us:"

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "services"
    subtitle = "E39Source is proud to offer Exceptional BMW Service"
    link_url = "service"
    link_text = "view services"

[params.recent_posts]
    enable = true
    title = "location"
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']
